---

name: mdbook-deploy

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout `carrie` (we hope)
        uses: ./.github/actions/checkout

      - name: misc
        run: nix build .

      - name: Build docs
        run: mdbook build

      - name: Deploy docs
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_EMPTY_COMMITS: true
          MESSAGE: '{long-sha}'
